env:
  es6: true
  node: true
  mocha: true

extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - off
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - warn
    -
      allow:
        - debug
        - warn
        - error
