GET http://127.0.0.1:3000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1YmJkMDgwNDAwN2E1ODM2NzAzNmRiNDUiLCJ1c2VybmFtZSI6InRlc3QtYWRtaW4iLCJpc0FkbWluIjp0cnVlLCJpc0FjdGl2ZSI6dHJ1ZSwiaWF0IjoxNTM5MjMwOTc4ODc4LCJleHAiOjE1MzkyMzgxNzh9.7ICMxkH-88omvwId_cNo3fKkhvZKDsm8Pi-3yLkE-jY